### ISSUE TITLE
Stackdriver exporters failing to detect GCE metadata api when run on Istio

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#199]
I think something's fundamentally wrong with Istio on GKE execution environment right now. This reproduces on HEAD with both Istio 1.0 and 1.1 (GKE Add-on).

Microservices are still failing to access metadata server after first 30s. They keep retrying. But when I exec into the pod, I can access the metadata API.

It's nondeterministic, sometimes registering tracing succeeds, but not profiling (basically similar metadata api calls trying to register if they're on GCE, if so trying to get a token).

This is a red flag if users are using Stackdriver Profiling/Debugger/Tracing or Opencensus exporers for Stackdriver on GKE w/ Istio.

Look at these logs:

`{"message":"failed to start profiler: failed to get the project ID from Compute Engine: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: connect: connection refused","severity":"warning","timestamp":"2019-03-08T22:54:23.649438404Z"}`

`{"message":"sleeping 10s to retry initializing stackdriver profiler","severity":"info","timestamp":"2019-03-08T22:54:23.649503248Z"}
{"message":"failed to initialize stackdriver exporter: stackdriver: no project found with application default credentials","severity":"info","timestamp":"2019-03-08T22:54:23.649674038Z"}`

`{"message":"sleeping 10s to retry initializing stackdriver exporter","severity":"info","timestamp":"2019-03-08T22:54:23.649687415Z"}`

`{"message":"failed to start profiler: failed to get the project ID from Compute Engine: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: connect: connection refused","severity":"warning","timestamp":"2019-03-08T22:54:33.649663529Z"}`

`{"message":"sleeping 20s to retry initializing stackdriver profiler","severity":"info","timestamp":"2019-03-08T22:54:33.650004528Z"}`

`{"message":"registered stackdriver tracing","severity":"info","timestamp":"2019-03-08T22:54:33.726637283Z"}` **TRACING REGISTRATION WORKED!**

`{"message":"failed to start profiler: failed to get the project ID from Compute Engine: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: connect: connection refused","severity":"warning","timestamp":"2019-03-08T22:54:53.650341347Z"}`

`{"message":"sleeping 30s to retry initializing stackdriver profiler","severity":"info","timestamp":"2019-03-08T22:54:53.650849836Z"}`

`{"message":"could not initialize stackdriver profiler after retrying, giving up","severity":"warning","timestamp":"2019-03-08T22:55:23.651187113Z"}` **PROFILER GAVE UP!**

Any help debugging is appreciated.
cc: @askmeegs

**Comment by ahmetb** [comment]
this is copied from https://github.com/GoogleCloudPlatform/microservices-demo/pull/183#issuecomment-471088780

**Comment by ahmetb** [comment]
I think in https://github.com/GoogleCloudPlatform/microservices-demo/blob/57b316c0455f69d314f9e80d59b88493c3ea508e/release/istio-manifests.yaml we should also whitelist `metadata.google` and `metadata` hostnames too, as some client libraries might be using those. But I'm not sure.

**Comment by askmeegs** [comment]
relevant: https://github.com/kubernetes/kubernetes/issues/65502

**Comment by ahmetb** [comment]
Sort of relevant, but not the cause. It's not explaining why it's taking almost 30 seconds to work (and sometimes longer). Also istio has always started the istio-proxy sidecar container in non-deterministic order, but this was reliably working at some point.

**Comment by askmeegs** [comment]
Testing in my GKE environment now, observations: 

Re: suspicion on this being a `ServiceEntry` problem:
- Istio now [allows](https://istio.io/docs/reference/config/installation-options/#global-options) outbound traffic by default. I verified that `istio-demo.yaml` ([manual OSS quickstart](https://istio.io/docs/setup/kubernetes/install/kubernetes/#installation-steps)) installation uses this default, and so does Istio on GKE. **Meaning** -- when I delete the serviceentries (GCE metadata IP), this behavior is unchanged. (nondeterministic stackdriver startup failure.) 
- So I don't think it's a serviceEntry issue -- evidenced by, you can exec into the `server` container (**after** the sidecar envoy starts), start the binary, works fine / can reach GCE metadata server. 

This tells me that the order of envoy + `server` containers starting the pod is what's causing this behavior. My hypothesis is that at the time a service calls `initProfiler`, etc., the [initContainer](https://istio.io/blog/2019/data-plane-setup/#sidecar-injection) modifying iptables is done (outbound traffic is intercepted) but envoy is not ready to handle it. 

Evidenced by, when I add 20-second `time.sleep` to `productcatalog`, before `initProfiler` runs, that function reliably succeeds: 

```
productcatalogservice-5ffd9786df-n6hwm server {"message":"started stackdriver profiler","severity":"info","timestamp":"2019-05-03T17:46:37.011587403Z"}
```

Which is "this was reliably working at some point" is confusing to me right now, because if the 2 containers in the pod (istio-proxy and `server`) always started up in parallel, we should have been seeing this bug intermittently all along. 

**possible solutions** -- 
- change the `readiness` probes on these services to successfully curl an external endpoint (GCE metadata server) (but this would require removing grpc health probe? because to my knowledges, you can't have 2 readiness probes) 
- improve the retry policies for each service, for the stackdriver exporter startup. [example](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/productcatalogservice/server.go#L189) -

**Comment by askmeegs** [comment]
Another possible temporary solution: add small (5-second) sleeps before calling `initProfiler` on any of the services that are instrumented with it. 

(Tested this with `checkoutservice` and `productcatalog`, changing nothing else about the `ServiceEntries`, and works for now.)

**Comment by ahmetb** [comment]
But the same thing would happen on tracing, too? And above, tracing worked but profiler still fails in the same process. That's the part I couldn't explain.

**Comment by askmeegs** [comment]
Right - tracing seems to recover during retries, but profiler does not. This makes me think something specifically weird happens on [`profiler.Start`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/productcatalogservice/server.go#L190) 

 If the hypothesis is that envoy is blocking valid outbound connections as both containers (`server` and `istio-proxy`) start up), then subsequent retries for `169.254.169.254` **should** succeed. (This is the call `profiler.Start` makes) But subsequent retries fail:

```
 Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: connect: connection refused"
```

I've increased the total # of retries here, I've reduced the sleep between the retries -- still fails. 
But if (during this `initProfiler` retry loop) I exec into the server container and `curl` that same path, it succeeds. This makes me think something "sticky" is happening in the call to `profiler.Start` -- or that the ip:port it *says* it's trying to reach isn't what the request actually is. 

The underlying `getProjectID` call **does** use `169.254.169.254` by default [[src](https://github.com/googleapis/google-cloud-go/blob/master/compute/metadata/metadata.go#L39)] but I'm wondering if something is overriding that. And the log is using the default ip:port.

**Comment by kalyanac** [comment]
> I've increased the total # of retries here, I've reduced the sleep between the retries -- still fails.
This happens because of a bug in Go Profiler agent Start(). A [fix](https://github.com/googleapis/google-cloud-go/commit/ef4feff11299ec7d9d361603b09862e311a48186) is submitted and this should fix the problem with retries. 

If you rebuild your containers, Profiler should start successfully.

That is assuming that the Istio service entries are properly setup. Here are mine:

```apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-googleapis
spec:
  hosts:
  - "accounts.google.com" # Used to get token
  - "*.googleapis.com"
  ports:
  - number: 80
    protocol: HTTP
    name: http
  - number: 443
    protocol: HTTPS
    name: https
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-metadata-server
spec:
  hosts:
  - metadata.google.internal
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_INTERNAL
  resolution: DNS```

**Comment by kalyanac** [comment]
I've also tested all the other agents with Istio and they all work fine. There maybe a delay in startup if the Profiler tries to intialize before the istio-proxy is up and running. In my experiments, they all started successfully after 1-3 tries with 1 second sleep between retries.

**Comment by askmeegs** [comment]
Hi Kalyana, thank you for this! I've upgraded one of the Go service's dependencies to 

```
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.39.0"
```

based on: https://github.com/googleapis/google-cloud-go/releases

(I'm using the same service entries as yours.)
And I re-ran `dep ensure`, then rebuilt/pushed the container. But I'm still seeing the Profiler repeatedly fail to start -- 

```
productcatalogservice-574644df9c-5894h server {"message":"sleeping 1s to retry initializing stackdriver profiler","severity":"info","timestamp":"2019-05-23T15:56:25.803424805Z"}
productcatalogservice-574644df9c-5894h server {"message":"could not initialize stackdriver profiler after retrying, giving up","severity":"warning","timestamp":"2019-05-23T15:56:26.803748156Z"}
```

Is there something I'm missing here re: updating the version of Profiler we're using?

**Comment by kalyanac** [comment]
0.39.0 doesnt have the patch yet.
https://github.com/googleapis/google-cloud-go/compare/v0.39.0...master

Also, I spoke too soon. 

We also made fixes to Node.js agent, a new release will happen shortly. 
We are working on adding retry for Java agent, testing right now.

**Comment by kalyanac** [comment]
Node.JS agent [v2.0.1](https://github.com/googleapis/cloud-profiler-nodejs/releases/tag/v2.0.1) is released. Please try with that version once it is published to npm.

**Comment by askmeegs** [comment]
re: Go, I've had some dependency issues when using the `master` branch in `Gopkg.toml` -- will wait for the next release to put out a PR for this.

**Comment by kalyanac** [comment]
All agents now work as long as the host "metadata.google.internal." (with the trailing dot) is whitelisted, Istio needs to have this [PR](https://github.com/istio/istio/pull/14405)

**Comment by askmeegs** [comment]
@kalyanac  it seems that the new google-cloud-go library and the existing OpenCensus library in this app aren't playing well together.

upgraded to google-cloud-go 0.41.0 -- https://github.com/askmeegs/microservices-demo/blob/profiler3/src/productcatalogservice/Gopkg.toml#L30 

Getting a build error from opencensus: 

```
# github.com/GoogleCloudPlatform/microservices-demo/src/productcatalogservice/vendor/contrib.go.opencensus.io/exporter/stackdriver
vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go:357:17: metric.GetName undefined (type *"github.com/GoogleCloudPlatform/microservices-demo/src/productcatalogservice/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric has no field or method GetName)
```

Then per these instructions -- https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/101  I upgraded the opencensus stackdriver exporter to 0.9.2, but then on `dep ensure` -- 

```
Solving failure: No versions of contrib.go.opencensus.io/resource met constraints:
	v0.1.1: Could not introduce contrib.go.opencensus.io/resource@v0.1.1, as its subpackage contrib.go.opencensus.io/resource/resourcekeys is missing. (Package is required by contrib.go.opencensus.io/exporter/stackdriver@v0.9.2.)
	v0.1.0: Could not introduce contrib.go.opencensus.io/resource@v0.1.0, as its subpackage contrib.go.opencensus.io/resource/resourcekeys is missing. (Package is required by contrib.go.opencensus.io/exporter/stackdriver@v0.9.2.)
	v0: Could not introduce contrib.go.opencensus.io/resource@v0, as its subpackage contrib.go.opencensus.io/resource/resourcekeys is missing. (Package is required by contrib.go.opencensus.io/exporter/stackdriver@v0.9.2.)
	master: Could not introduce contrib.go.opencensus.io/resource@master, as its subpackage contrib.go.opencensus.io/resource/resourcekeys is missing. (Package is required by contrib.go.opencensus.io/exporter/stackdriver@v0.9.2.)
	cmd: Could not introduce contrib.go.opencensus.io/resource@cmd, as its subpackage contrib.go.opencensus.io/resource/resourcekeys is missing. (Package is required by contrib.go.opencensus.io/exporter/stackdriver@v0.9.2.)
```

Have you seen similar compatibility issues between google-cloud-go and opencensus? Thanks!

**Comment by kalyanac** [comment]
No I havent seen this but also I havent tried with 0.41.0. 
Do you need to use a newer version of OpenCensus?

**Comment by ahmetb** [comment]
@askmeegs Have you verified the fix manually? do all exporters register just fine in the pod logs while running on Istio now?

I'm unclear about:
- what was the issue to begin with (since this used to work with the locked dependency versions)
- why it broke, and
- how does bumping the dependencies fix it (and whether bumping Go/Node dependencies are sufficient given we have other languages as well)
